# 1. Theme Activation (Choose Gem or Remote Theme)
# Use remote_theme if hosting directly on GitHub Pages
# remote_theme: "mmistakes/minimal-mistakes@4.28.0"

title: "Bienvenue sur le site de Vinny1111"
# description: Modernist is a theme for GitHub Pages.
show_downloads: False
display: none
theme: jekyll-theme-modernist # Uncomment instead if using local Ruby Gem

# 2. Appearance Skin
# Options: "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# minimal_mistakes_skin: "default"

description: ""

